[project]
name = "NDA"
version = "1.0.5"
description = "Nade Desktop App - Wiring audio streams"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.20.0",
    "sounddevice>=0.4.6",
    "soundcard>=0.4.2",
]
